local cmd = vim.cmd
cmd("highlight NormalFloat guibg=#ffffff00 guifg=#ffffff00")
cmd("highlight LineNrBelow guifg=#aaaaaa")
cmd("highlight LineNrAbove guifg=#aaaaaa")
cmd("highlight LineNr guifg=#06e0ff")
cmd("highlight TelescopeSelectionCaret guifg=#9999ff guibg=#3e75aa")
cmd("highlight TelescopeTitle guifg=#9999ff")
cmd("highlight TelescopePromptCounter guifg=#9999ff")
cmd("highlight VertSplit guifg=#f9f90f")
cmd("highlight NeoTreeWinSeparator guifg=#000000")
cmd("highlight StatusLine guibg=none")
cmd("highlight LazyH1 guifg=#16b0ff")
cmd("highlight LazyButton guifg=#84C9EF")
cmd("highlight CursorLine guibg=#c0caf5")
cmd("highlight NeoTreeCursorLine guibg=#c0caf5 guifg=#111111")
cmd("highlight Folded guibg=None guifg=#A1D9E0")
