local bo = vim.bo
local g = vim.g
local set = vim.o
local opt = vim.opt
local wo = vim.wo
g.encoding = "UTF-8"
set.fileencoding = "utf-8"
set.scrolloff = 3
set.sidescrolloff = 3
wo.number = true
wo.relativenumber = true
wo.cursorline = false
wo.signcolumn = "yes"
bo.tabstop = 2
set.tabstop = 2
set.softtabstop = 2
set.shiftround = true
set.shiftwidth = 2
bo.shiftwidth = 2
set.expandtab = true
bo.expandtab = true
set.autoindent = true
bo.autoindent = true
set.smartindent = true
set.ignorecase = true
set.smartcase = true
set.hlsearch = false
set.incsearch = true
set.autoread = true
bo.autoread = true
wo.wrap = true
set.whichwrap = "<,>,[,]"
set.hidden = true
set.mouse = "a"
set.backup = false
set.writebackup= false
set.swapfile = false
set.updatetime = 300
set.timeoutlen = 500
set.splitbelow = true
set.splitright = true
g.completeopt = "menu,menuone,noselect,noinsert"
opt.termguicolors = true
set.list  = false
set.listchars = "space: ,tab:  "
set.fillchars = "eob: ,fold: "
set.wildmenu = false
set.pumheight = 10
set.showtabline = 2
set.showmode = true
opt.clipboard = "unnamedplus"
set.cmdheight = 0
set.wrap = false
set.shortmess = set.shortmess .. 'aoscTWIF'
